import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import '../session.dart';

class PaymentPage extends StatefulWidget {final String baseUrl,date,time;final Map<String,dynamic> location,car,service;final List<Map<String,dynamic>> addOns;final double total;const PaymentPage({super.key,required this.baseUrl,required this.location,required this.car,required this.service,required this.addOns,required this.total,required this.date,required this.time});@override State<PaymentPage> createState()=>_PaymentPageState();}
class _PaymentPageState extends State<PaymentPage>{String method='cash';bool sending=false;String? error;
  Future<void> submit()async{setState(()=>sending=true);final r=await http.post(Uri.parse('${widget.baseUrl}/api/bookings/'),headers:Session.authHeaders,body:jsonEncode({'car':widget.car['id'],'service':widget.service['id'],'car_size':widget.car['size'],'address_text':widget.location['address_text'],'latitude':widget.location['latitude'],'longitude':widget.location['longitude'],'date':widget.date,'time_slot':widget.time,'payment_method':method,'add_ons':widget.addOns.map((x)=>{'id':x['id'],'quantity':x['quantity']}).toList()}));if(!mounted)return;if(r.statusCode==201){showDialog(context:context,barrierDismissible:false,builder:(c)=>AlertDialog(icon:const Icon(Icons.check_circle,color:Colors.green,size:55),title:const Text('تم تأكيد طلبك'),content:const Text('يمكنك متابعة حالة الطلب من صفحة الطلبات.'),actions:[FilledButton(onPressed:()=>Navigator.popUntil(context,(route)=>route.isFirst),child:const Text('العودة للرئيسية'))]));}else{setState(()=>error='تعذر تأكيد الطلب، تحقق من أن الوقت ما زال متاحًا.');}setState(()=>sending=false);}
  @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('الدفع')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('ملخص الطلب',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:12),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[row('الخدمة',widget.service['name']),...widget.addOns.map((x)=>row(x['name'],'${x['quantity']} × ${x['price']} ر.س')),row('المركبة',widget.car['vehicle_name'] ?? widget.car['brand']),row('الموقع',widget.location['name']),row('الموعد','${widget.date} • ${widget.time}'),const Divider(),row('الإجمالي','${widget.total.toStringAsFixed(2)} ر.س')]))),const SizedBox(height:20),const Text('طريقة الدفع',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),RadioListTile(value:'cash',groupValue:method,onChanged:(v)=>setState(()=>method=v!),title:const Text('كاش')),RadioListTile(value:'card',groupValue:method,onChanged:(v)=>setState(()=>method=v!),title:const Text('شبكة عند الوصول')),RadioListTile(value:'bank_transfer',groupValue:method,onChanged:(v)=>setState(()=>method=v!),title:const Text('تحويل بنكي')),if(error!=null)Text(error!,style:const TextStyle(color:Colors.red)),const SizedBox(height:12),FilledButton(onPressed:sending?null:submit,child:sending?const CircularProgressIndicator():const Text('تأكيد الدفع والطلب'))])));
  Widget row(String a,dynamic b)=>Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(a),Flexible(child:Text('$b',style:const TextStyle(fontWeight:FontWeight.bold)))]));
}
